"""agregar gastos

Revision ID: 1f003b2ab723
Revises: 80add26d6b0c
Create Date: 2026-09-07 19:28:19.288824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f003b2ab723'
down_revision: Union[str, None] = '80add26d6b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo IN ('CORRIENTE','NO_CORRIENTE')", name='ck_categoria_gasto_tipo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('categoria_gasto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('medio_pago', sa.String(length=20), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_numero', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.String(length=1000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("medio_pago IN ('EFECTIVO','DEBITO','CREDITO','TRANSFERENCIA')", name='ck_gasto_medio_pago'),
    sa.CheckConstraint('monto > 0', name='ck_gasto_monto'),
    sa.ForeignKeyConstraint(['categoria_gasto_id'], ['categoria_gasto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed de categorías de gasto, mismos defaults que la app vieja (apk-stock).
    categoria_gasto = sa.table(
        'categoria_gasto',
        sa.column('nombre', sa.String),
        sa.column('tipo', sa.String),
        sa.column('descripcion', sa.String),
        sa.column('activo', sa.Boolean),
    )
    op.bulk_insert(categoria_gasto, [
        {'nombre': 'Alquiler', 'tipo': 'CORRIENTE', 'descripcion': 'Alquiler mensual del local', 'activo': True},
        {'nombre': 'Servicios', 'tipo': 'CORRIENTE', 'descripcion': 'Luz, agua, gas, internet', 'activo': True},
        {'nombre': 'Sueldos', 'tipo': 'CORRIENTE', 'descripcion': 'Sueldos y cargas sociales', 'activo': True},
        {'nombre': 'Impuestos', 'tipo': 'CORRIENTE', 'descripcion': 'AFIP, IIBB, municipales', 'activo': True},
        {'nombre': 'Mercadería', 'tipo': 'CORRIENTE', 'descripcion': 'Compra de stock para reventa', 'activo': True},
        {'nombre': 'Marketing', 'tipo': 'CORRIENTE', 'descripcion': 'Publicidad y redes sociales', 'activo': True},
        {'nombre': 'Limpieza', 'tipo': 'CORRIENTE', 'descripcion': 'Insumos de limpieza', 'activo': True},
        {'nombre': 'Mobiliario', 'tipo': 'NO_CORRIENTE', 'descripcion': 'Compra de muebles y exhibidores', 'activo': True},
        {'nombre': 'Equipamiento', 'tipo': 'NO_CORRIENTE', 'descripcion': 'Tablets, impresoras, lectores', 'activo': True},
        {'nombre': 'Reformas', 'tipo': 'NO_CORRIENTE', 'descripcion': 'Pintura, refacciones del local', 'activo': True},
        {'nombre': 'Maquinaria', 'tipo': 'NO_CORRIENTE', 'descripcion': 'Máquinas de coser, planchas', 'activo': True},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasto')
    op.drop_table('categoria_gasto')
    # ### end Alembic commands ###
