"""agregar proveedor

Revision ID: 449a603279f8
Revises: 4f869b25d301
Create Date: 2026-09-07 18:43:43.847534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449a603279f8'
down_revision: Union[str, None] = '4f869b25d301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('cuit', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.String(length=1000), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # batch_alter_table: en SQLite no se puede agregar una FK con ALTER TABLE
    # directo (hay que recrear la tabla); batch mode lo resuelve y en
    # Postgres funciona igual sin cambios.
    with op.batch_alter_table('producto') as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_producto_proveedor_id', 'proveedor', ['proveedor_id'], ['id'], ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto') as batch_op:
        batch_op.drop_constraint('fk_producto_proveedor_id', type_='foreignkey')
        batch_op.drop_column('proveedor_id')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
