"""agregar ventas

Revision ID: 80add26d6b0c
Revises: 449a603279f8
Create Date: 2026-09-07 19:12:49.361371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80add26d6b0c'
down_revision: Union[str, None] = '449a603279f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_medio_pago',
    sa.Column('medio_pago', sa.String(length=20), nullable=False),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recargo_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.Column('arancel_banco_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint("medio_pago IN ('EFECTIVO','DEBITO','CREDITO','TRANSFERENCIA')", name='ck_config_medio_pago_medio_pago'),
    sa.PrimaryKeyConstraint('medio_pago')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.String(length=2000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('COMPLETADA','ANULADA','PARCIAL_DEVUELTA')", name='ck_venta_estado'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('medio_pago', sa.String(length=20), nullable=False),
    sa.Column('monto_subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recargo_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cuotas', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("medio_pago IN ('EFECTIVO','DEBITO','CREDITO','TRANSFERENCIA')", name='ck_pago_venta_medio_pago'),
    sa.CheckConstraint('monto > 0', name='ck_pago_venta_monto'),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_item', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_detalle_venta_cantidad'),
    sa.ForeignKeyConstraint(['variante_id'], ['variante_producto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed de medios de pago, mismos defaults que la app vieja (apk-stock).
    config_medio_pago = sa.table(
        'config_medio_pago',
        sa.column('medio_pago', sa.String),
        sa.column('descuento_porcentaje', sa.Numeric),
        sa.column('recargo_porcentaje', sa.Numeric),
        sa.column('habilitado', sa.Boolean),
        sa.column('arancel_banco_porcentaje', sa.Numeric),
    )
    op.bulk_insert(config_medio_pago, [
        {'medio_pago': 'EFECTIVO', 'descuento_porcentaje': 20, 'recargo_porcentaje': 0, 'habilitado': True, 'arancel_banco_porcentaje': 0},
        {'medio_pago': 'TRANSFERENCIA', 'descuento_porcentaje': 15, 'recargo_porcentaje': 0, 'habilitado': True, 'arancel_banco_porcentaje': 0},
        {'medio_pago': 'DEBITO', 'descuento_porcentaje': 0, 'recargo_porcentaje': 0, 'habilitado': True, 'arancel_banco_porcentaje': 0},
        {'medio_pago': 'CREDITO', 'descuento_porcentaje': 0, 'recargo_porcentaje': 0, 'habilitado': True, 'arancel_banco_porcentaje': 0},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_venta')
    op.drop_table('pago_venta')
    op.drop_table('venta')
    op.drop_table('config_medio_pago')
    # ### end Alembic commands ###
